### ISSUE TITLE
v2 requirements

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/n-video#11]
Thought I'd start a list of use cases for videos as, rather than hacking too much at n-video to mess it up and get it to do what I want for the video challenge, it makes more sense to have the challenge inform the next major version. Please add any current uses I've missed and any other experiments we definitely want to pursue so

1. Display a video given a video id (article page)
2. Given a stream identifier fetch a selection of related videos, display a placeholder image and play button and init video on demand (related in stream)
3. Given some video ids query the video api to find information about them, sort/filter according to some criteria then construct video players for each ('view as video stream' from the challenge)
4. Initialise with minimal markup i.e. provide a container element and then n-video does everything else
5. Initialise with data already fetched from video api

@ironsidevsquincy @tom-parker @matthew-andrews @commuterjoy

**Comment by ironsidevsquincy** [comment]
It already does 1 and 4, right?
Agree with 5
Guess it depends on how it looks, but feels like 2 and 3 should actually be a separate component (video-grid?) that just uses n-video. Basically the only thing I wanted n-video to do was turn a single marked-up div into a video player (similar to o-comments)

**Comment by wheresrhys** [comment]
It does 1.  I agree with your assessment of 2 and 3, but to avoid extra requests we'd need to implement 5. By 4 I mainly meant initialising multiple videos (so that would fall under the gallery component), but n-video doesn't quite do 4 for a single video as init and videoFactory expect certain data attributes to be present, though it's not far off.

I may have a go at making a gallery component tomorrow cc @keirog (though style-wise, nothing much new - just scaling up what darren already did in streams)

**Comment by ironsidevsquincy** [comment]
> init and videoFactory expect certain data attributes to be present, though it's not far off.

Right, yeah, always expected it to run over multiple videos so the only way to pass in data was to use attributes

**Comment by wheresrhys** [comment]
I've now implemented a first stab at a video stream in dobi. Once we've polished up the design and worked out what's good about it will move into a component. point 5 above is now available in v2.7
