### ISSUE TITLE
Sass fails to build on build service

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/n-video#40]
These fail:

- http://build.origami.ft.com/v2/bundles/css?modules=n-video@4
- http://build.origami.ft.com/v2/bundles/css?modules=n-video@3

```
/*

Cannot complete build due to compilation error from build tools:

.../bower_components/n-video/main.scss
Error: argument `$color` of `rgba($color, $alpha)` must be a color

       Backtrace:
       	.../bower_components/n-video/main.scss:31, in function `rgba`
       	.../bower_components/n-video/main.scss:31
        on line 31 of .../bower_components/n-video/main.scss
>> 		background-color: rgba(getColor('grey-tint4'), 0.9);
   --------------------^



*/
```

But this old version works:

- http://build.origami.ft.com/v2/bundles/css?modules=n-video@2

**Comment by callumlocke** [comment]
Also getting this when building locally, it's not just the build service.

**Comment by callumlocke** [comment]
oh it looks like we just needed to `@import 'next-sass-setup/main'` first.

should this be done by the module itself, so it can build by itself over the build service? or is build service not meant to be used for n-* modules?

**Comment by ironsidevsquincy** [comment]
`n-*` components haven't really been built with the build service in mine. However, they should be self-contained things that should pull in everything they need, so this is a bug

Solution would be to require `o-color`, and use `oColorsGetPaletteColor` instead

**Comment by lc512k** [comment]
Please raise on [o-video](https://github.com/Financial-Times/o-video/issues) if still an issue.
